spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

payment:
  service:
    url: http://localhost:8082
# Базовая конфигурация SpringDoc
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
        exclude:
      base-path: /actuator
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      orderServiceRetry:
        max-attempts: 3
        wait-duration: 10s
        retry-exceptions:
          - "feign.FeignException$InternalServerError"
        ignore-exceptions:
          - java.lang.IllegalArgumentException

  circuitbreaker:
    instances:
      orderServiceCircuitBreaker:
        record-exceptions:
          - "feign.FeignException$InternalServerError"
        ignore-exceptions:
          - java.lang.IllegalArgumentException
        failure-rate-threshold: 50
        sliding-window-size: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 10
        minimum-number-of-calls: 10
  bulkhead:
    instances:
      orderServiceBulkhead:
        max-concurrent-calls: 5
        max-wait-duration: 2s
  ratelimiter:
    instances:
      orderServiceRateLimiter:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 1s

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    org.springframework.aop: DEBUG